FROM docker.io/ros:noetic-ros-base-focal

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      ca-certificates \
      git \
      pkg-config \
      python3-venv \
      python3.8-venv && \
    rm -rf /var/lib/apt/lists/*

RUN rosdep update --rosdistro "$ROS_DISTRO"

WORKDIR /opt/open_mower_ros
COPY src /opt/open_mower_ros/src

RUN rosdep install --from-paths src --ignore-src --simulate | \
    sed --expression '1d' | sort | tr -d '\n' | sed --expression 's/  apt-get install//g' > /apt-install_list && \
    apt-get update && \
    apt-get install --no-install-recommends --yes $(cat /apt-install_list) libasio-dev libcrypto++-dev libcrypto++6 && \
    rm -rf /var/lib/apt/lists/* /apt-install_list

RUN mkdir -p /config
COPY docker/assets/rosconsole.config /config/rosconsole.config
